#!/usr/bin/env node

var cn = require('../lib');

var opts = {
  runtime: "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome",
  files: "../ui",
  port: 8080,
  index: "/index.html",
  width: 1024,
  height: 760
};

cn(opts, function(websocket, chrome) {

  websocket.on('message', function(message) {
    console.log(message);
  });

  chrome.stdout.on('data', function (data) {

  });

  chrome.stderr.on('data', function (data) {

  });

  chrome.on('exit', function (code) {
    process.exit(0);
  });
});
